/// Insurance Policy Model
library;

class InsurancePolicy {
  final String id;
  final String insurer;
  final String name;
  final String type;
  final String category;
  final double premiumMonthly;
  final double premiumYearly;
  final double coverageAmount;
  final double claimSettlementRatio;
  final List<String> benefits;
  final List<String> exclusions;
  final List<String> riders;
  final String suitableFor;
  final String notIdealFor;
  final int readabilityScore;
  final int riskScore;
  final String iconUrl;

  const InsurancePolicy({
    required this.id,
    required this.insurer,
    required this.name,
    required this.type,
    required this.category,
    required this.premiumMonthly,
    required this.premiumYearly,
    required this.coverageAmount,
    required this.claimSettlementRatio,
    required this.benefits,
    required this.exclusions,
    required this.riders,
    required this.suitableFor,
    required this.notIdealFor,
    required this.readabilityScore,
    required this.riskScore,
    required this.iconUrl,
  });

  factory InsurancePolicy.fromJson(Map<String, dynamic> json) {
    return InsurancePolicy(
      id: json['id'] ?? '',
      insurer: json['insurer'] ?? '',
      name: json['name'] ?? '',
      type: json['type'] ?? '',
      category: json['category'] ?? '',
      premiumMonthly: (json['premiumMonthly'] ?? 0).toDouble(),
      premiumYearly: (json['premiumYearly'] ?? 0).toDouble(),
      coverageAmount: (json['coverageAmount'] ?? 0).toDouble(),
      claimSettlementRatio: (json['claimSettlementRatio'] ?? 0).toDouble(),
      benefits: List<String>.from(json['benefits'] ?? []),
      exclusions: List<String>.from(json['exclusions'] ?? []),
      riders: List<String>.from(json['riders'] ?? []),
      suitableFor: json['suitableFor'] ?? '',
      notIdealFor: json['notIdealFor'] ?? '',
      readabilityScore: json['readabilityScore'] ?? 5,
      riskScore: json['riskScore'] ?? 5,
      iconUrl: json['iconUrl'] ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'insurer': insurer,
      'name': name,
      'type': type,
      'category': category,
      'premiumMonthly': premiumMonthly,
      'premiumYearly': premiumYearly,
      'coverageAmount': coverageAmount,
      'claimSettlementRatio': claimSettlementRatio,
      'benefits': benefits,
      'exclusions': exclusions,
      'riders': riders,
      'suitableFor': suitableFor,
      'notIdealFor': notIdealFor,
      'readabilityScore': readabilityScore,
      'riskScore': riskScore,
      'iconUrl': iconUrl,
    };
  }
}

// Sample policy data for demo - 50 realistic Indian insurance policies
class SamplePolicies {
  static const List<Map<String, dynamic>> policies = [
    // ==================== LIFE INSURANCE ====================
    {
      'id': 'LIF001',
      'insurer': 'LIC',
      'name': 'Jeevan Anand',
      'type': 'Life Insurance',
      'category': 'Individual',
      'premiumMonthly': 2500,
      'premiumYearly': 28000,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 98.5,
      'benefits': ['Death Benefit', 'Maturity Benefit', 'Bonus Accumulation', 'Loan Facility'],
      'exclusions': ['Suicide within 1 year'],
      'riders': ['Accidental Death Benefit', 'Critical Illness'],
      'suitableFor': 'Young professionals, First-time buyers',
      'notIdealFor': 'Senior citizens above 55',
      'readabilityScore': 7,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'LIF002',
      'insurer': 'LIC',
      'name': 'Jeevan Labh',
      'type': 'Life Insurance',
      'category': 'Individual',
      'premiumMonthly': 3000,
      'premiumYearly': 34000,
      'coverageAmount': 1500000,
      'claimSettlementRatio': 98.5,
      'benefits': ['Guaranteed Additions', 'Maturity Benefit', 'Death Benefit'],
      'exclusions': ['Suicide within 1 year', 'War risks'],
      'riders': ['Accidental Death', 'Premium Waiver'],
      'suitableFor': 'Long-term savers, Conservative investors',
      'notIdealFor': 'Those seeking high returns',
      'readabilityScore': 6,
      'riskScore': 2,
      'iconUrl': '',
    },
    {
      'id': 'LIF003',
      'insurer': 'SBI Life',
      'name': 'Smart Platina Plus',
      'type': 'Life Insurance',
      'category': 'Individual',
      'premiumMonthly': 4000,
      'premiumYearly': 45000,
      'coverageAmount': 2000000,
      'claimSettlementRatio': 97.2,
      'benefits': ['Wealth Boosters', 'Loyalty Additions', 'Flexible Premium'],
      'exclusions': ['Pre-existing terminal illness'],
      'riders': ['Critical Illness', 'Waiver of Premium'],
      'suitableFor': 'HNIs, Long-term wealth builders',
      'notIdealFor': 'Short-term investors',
      'readabilityScore': 7,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'LIF004',
      'insurer': 'Max Life',
      'name': 'Whole Life Super',
      'type': 'Life Insurance',
      'category': 'Individual',
      'premiumMonthly': 5500,
      'premiumYearly': 62000,
      'coverageAmount': 2500000,
      'claimSettlementRatio': 99.2,
      'benefits': ['Lifetime Coverage', 'Guaranteed Maturity', 'Bonus'],
      'exclusions': ['Hazardous activities'],
      'riders': ['Hospital Cash', 'Critical Illness'],
      'suitableFor': 'Those seeking lifetime protection',
      'notIdealFor': 'Young single individuals',
      'readabilityScore': 8,
      'riskScore': 2,
      'iconUrl': '',
    },
    
    // ==================== TERM INSURANCE ====================
    {
      'id': 'TRM001',
      'insurer': 'HDFC Life',
      'name': 'Click2Protect Plus',
      'type': 'Term Insurance',
      'category': 'Individual',
      'premiumMonthly': 1200,
      'premiumYearly': 13500,
      'coverageAmount': 5000000,
      'claimSettlementRatio': 99.1,
      'benefits': ['High Coverage', 'Online Discount', 'Flexible Term', 'Income Option'],
      'exclusions': ['Pre-existing illness not disclosed'],
      'riders': ['Waiver of Premium', 'Income Benefit', 'Critical Illness'],
      'suitableFor': 'Budget-conscious families, High coverage seekers',
      'notIdealFor': 'Those seeking maturity benefits',
      'readabilityScore': 8,
      'riskScore': 2,
      'iconUrl': '',
    },
    {
      'id': 'TRM002',
      'insurer': 'ICICI Prudential',
      'name': 'iProtect Smart',
      'type': 'Term Insurance',
      'category': 'Family',
      'premiumMonthly': 1500,
      'premiumYearly': 17000,
      'coverageAmount': 7500000,
      'claimSettlementRatio': 97.8,
      'benefits': ['Return of Premium Option', 'Life Stage Benefit', 'Increasing Cover'],
      'exclusions': ['Self-inflicted injuries'],
      'riders': ['Terminal Illness', 'Disability Cover', 'Accidental Death'],
      'suitableFor': 'Growing families, Long-term planners',
      'notIdealFor': 'Single individuals without dependents',
      'readabilityScore': 6,
      'riskScore': 2,
      'iconUrl': '',
    },
    {
      'id': 'TRM003',
      'insurer': 'Max Life',
      'name': 'Smart Secure Plus',
      'type': 'Term Insurance',
      'category': 'Individual',
      'premiumMonthly': 1100,
      'premiumYearly': 12500,
      'coverageAmount': 10000000,
      'claimSettlementRatio': 99.3,
      'benefits': ['Highest Claim Settlement', 'Joint Life Option', 'Cover Till 85'],
      'exclusions': ['Suicide within 12 months'],
      'riders': ['Waiver of Premium', 'Accidental Death'],
      'suitableFor': 'Sole breadwinners, Young families',
      'notIdealFor': 'Retirees',
      'readabilityScore': 9,
      'riskScore': 1,
      'iconUrl': '',
    },
    {
      'id': 'TRM004',
      'insurer': 'Tata AIA',
      'name': 'Sampoorna Raksha Supreme',
      'type': 'Term Insurance',
      'category': 'Individual',
      'premiumMonthly': 1300,
      'premiumYearly': 14800,
      'coverageAmount': 7500000,
      'claimSettlementRatio': 98.7,
      'benefits': ['Death Benefit', 'Terminal Illness', 'Premium Return'],
      'exclusions': ['Adventure sports deaths'],
      'riders': ['Critical Illness', 'Hospital Care'],
      'suitableFor': 'Middle-income families, New parents',
      'notIdealFor': 'Senior citizens',
      'readabilityScore': 7,
      'riskScore': 2,
      'iconUrl': '',
    },
    {
      'id': 'TRM005',
      'insurer': 'Bajaj Allianz',
      'name': 'eTouch Term Plan',
      'type': 'Term Insurance',
      'category': 'Individual',
      'premiumMonthly': 950,
      'premiumYearly': 10800,
      'coverageAmount': 5000000,
      'claimSettlementRatio': 98.2,
      'benefits': ['Lowest Premium', 'Online Only', 'Quick Issuance'],
      'exclusions': ['Pre-existing conditions'],
      'riders': ['Accidental Death', 'Income Benefit'],
      'suitableFor': 'Tech-savvy buyers, Budget seekers',
      'notIdealFor': 'Those wanting offline support',
      'readabilityScore': 8,
      'riskScore': 2,
      'iconUrl': '',
    },
    {
      'id': 'TRM006',
      'insurer': 'Kotak Life',
      'name': 'e-Term Plan',
      'type': 'Term Insurance',
      'category': 'Individual',
      'premiumMonthly': 1050,
      'premiumYearly': 11900,
      'coverageAmount': 7500000,
      'claimSettlementRatio': 98.0,
      'benefits': ['Online Discount', 'Whole Life Option', 'Level/Increasing Cover'],
      'exclusions': ['Hazardous sports'],
      'riders': ['Critical Illness', 'Waiver of Premium'],
      'suitableFor': 'Young professionals, IT employees',
      'notIdealFor': 'Those preferring branch service',
      'readabilityScore': 8,
      'riskScore': 2,
      'iconUrl': '',
    },
    
    // ==================== HEALTH INSURANCE - INDIVIDUAL ====================
    {
      'id': 'HLT001',
      'insurer': 'Star Health',
      'name': 'Comprehensive Health',
      'type': 'Health Insurance',
      'category': 'Individual',
      'premiumMonthly': 1200,
      'premiumYearly': 13500,
      'coverageAmount': 500000,
      'claimSettlementRatio': 96.8,
      'benefits': ['Cashless at 14000+ hospitals', 'Day Care', 'Pre & Post Hospitalization'],
      'exclusions': ['Cosmetic surgery', 'Dental', 'Infertility'],
      'riders': ['Personal Accident', 'Critical Illness'],
      'suitableFor': 'Young individuals, Self-employed',
      'notIdealFor': 'Families needing floater',
      'readabilityScore': 8,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'HLT002',
      'insurer': 'Care Health',
      'name': 'Care Advantage',
      'type': 'Health Insurance',
      'category': 'Individual',
      'premiumMonthly': 1000,
      'premiumYearly': 11500,
      'coverageAmount': 500000,
      'claimSettlementRatio': 95.5,
      'benefits': ['No Room Rent Limit', 'Wellness Benefits', 'Air Ambulance'],
      'exclusions': ['Pre-existing (4 year wait)', 'Mental illness'],
      'riders': ['OPD Cover', 'Maternity'],
      'suitableFor': 'Budget-conscious individuals',
      'notIdealFor': 'Those with pre-existing conditions',
      'readabilityScore': 7,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'HLT003',
      'insurer': 'HDFC Ergo',
      'name': 'Optima Secure',
      'type': 'Health Insurance',
      'category': 'Individual',
      'premiumMonthly': 1400,
      'premiumYearly': 15800,
      'coverageAmount': 750000,
      'claimSettlementRatio': 97.0,
      'benefits': ['Restore Benefit', 'Multiplier Benefit', 'Wellness Rewards'],
      'exclusions': ['Non-allopathic treatment', 'Obesity surgery'],
      'riders': ['Super Top-up', 'Hospital Cash'],
      'suitableFor': 'Corporate employees, Metro cities',
      'notIdealFor': 'Rural areas with limited network',
      'readabilityScore': 7,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'HLT004',
      'insurer': 'Niva Bupa',
      'name': 'Health Companion Individual',
      'type': 'Health Insurance',
      'category': 'Individual',
      'premiumMonthly': 1100,
      'premiumYearly': 12500,
      'coverageAmount': 500000,
      'claimSettlementRatio': 95.8,
      'benefits': ['Global Cover', 'Organ Donor Expenses', 'Ayush Treatment'],
      'exclusions': ['Experimental treatments'],
      'riders': ['Critical Illness', 'Personal Accident'],
      'suitableFor': 'NRIs, Frequent travelers',
      'notIdealFor': 'Those wanting domestic-only cover',
      'readabilityScore': 7,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'HLT005',
      'insurer': 'ICICI Lombard',
      'name': 'Complete Health Insurance',
      'type': 'Health Insurance',
      'category': 'Individual',
      'premiumMonthly': 1300,
      'premiumYearly': 14800,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 96.5,
      'benefits': ['Unlimited Restore', 'Cumulative Bonus', 'Modern Treatments'],
      'exclusions': ['Cosmetic procedures', 'Self-inflicted injuries'],
      'riders': ['OPD Care', 'Maternity Benefit'],
      'suitableFor': 'Comprehensive coverage seekers',
      'notIdealFor': 'Minimal coverage buyers',
      'readabilityScore': 8,
      'riskScore': 3,
      'iconUrl': '',
    },
    
    // ==================== HEALTH INSURANCE - FAMILY FLOATER ====================
    {
      'id': 'FAM001',
      'insurer': 'Star Health',
      'name': 'Family Health Optima',
      'type': 'Health Insurance',
      'category': 'Family',
      'premiumMonthly': 1800,
      'premiumYearly': 20000,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 96.5,
      'benefits': ['No Claim Bonus up to 100%', 'Day Care Procedures', 'Pre & Post Hospitalization'],
      'exclusions': ['Cosmetic surgery', 'Dental treatments'],
      'riders': ['Maternity Cover', 'OPD Cover', 'Personal Accident'],
      'suitableFor': 'Families with children, Nuclear families',
      'notIdealFor': 'Single individuals',
      'readabilityScore': 7,
      'riskScore': 4,
      'iconUrl': '',
    },
    {
      'id': 'FAM002',
      'insurer': 'Care Health',
      'name': 'Care Supreme',
      'type': 'Health Insurance',
      'category': 'Family',
      'premiumMonthly': 2200,
      'premiumYearly': 25000,
      'coverageAmount': 1500000,
      'claimSettlementRatio': 95.5,
      'benefits': ['Second Medical Opinion', 'Organ Donor', 'Road Ambulance'],
      'exclusions': ['Pre-existing (3 years)', 'War/Terrorism'],
      'riders': ['Super NCB', 'Unlimited Restore'],
      'suitableFor': 'Large families, Premium seekers',
      'notIdealFor': 'Budget buyers',
      'readabilityScore': 7,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'FAM003',
      'insurer': 'HDFC Ergo',
      'name': 'Optima Restore Family',
      'type': 'Health Insurance',
      'category': 'Family',
      'premiumMonthly': 2500,
      'premiumYearly': 28500,
      'coverageAmount': 2000000,
      'claimSettlementRatio': 97.0,
      'benefits': ['100% Sum Restore', 'Multiplier', 'Health Checkup'],
      'exclusions': ['Substance abuse', 'STDs'],
      'riders': ['Super Top-up', 'Critical Illness'],
      'suitableFor': 'Metro families, Corporate executives',
      'notIdealFor': 'Tier 3 cities',
      'readabilityScore': 8,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'FAM004',
      'insurer': 'Bajaj Allianz',
      'name': 'Health Guard Family Floater',
      'type': 'Health Insurance',
      'category': 'Family',
      'premiumMonthly': 1600,
      'premiumYearly': 18000,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 96.0,
      'benefits': ['Cashless Network', 'AYUSH', 'Domiciliary Treatment'],
      'exclusions': ['Pre-existing (4 years)', 'Maternity (9 months wait)'],
      'riders': ['Personal Accident', 'Hospital Cash'],
      'suitableFor': 'Value seekers, Middle-income families',
      'notIdealFor': 'Expecting parents',
      'readabilityScore': 7,
      'riskScore': 4,
      'iconUrl': '',
    },
    {
      'id': 'FAM005',
      'insurer': 'Max Bupa',
      'name': 'Health Recharge Family',
      'type': 'Health Insurance',
      'category': 'Family',
      'premiumMonthly': 2000,
      'premiumYearly': 22500,
      'coverageAmount': 1500000,
      'claimSettlementRatio': 95.2,
      'benefits': ['Recharge of Sum Insured', 'Wellness Benefits', 'E-Consultation'],
      'exclusions': ['Adventure sports injuries'],
      'riders': ['Maternity', 'OPD'],
      'suitableFor': 'Health-conscious families',
      'notIdealFor': 'Adventure enthusiasts',
      'readabilityScore': 8,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'FAM006',
      'insurer': 'Tata AIG',
      'name': 'MediCare Floater',
      'type': 'Health Insurance',
      'category': 'Family',
      'premiumMonthly': 1900,
      'premiumYearly': 21500,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 96.8,
      'benefits': ['Consumables Cover', 'Modern Treatment', 'Air Ambulance'],
      'exclusions': ['HIV/AIDS', 'Genetic disorders'],
      'riders': ['Critical Illness', 'Disability'],
      'suitableFor': 'Joint families, Multi-generation',
      'notIdealFor': 'Single-member coverage',
      'readabilityScore': 7,
      'riskScore': 3,
      'iconUrl': '',
    },
    
    // ==================== HEALTH INSURANCE - SENIOR CITIZEN ====================
    {
      'id': 'SEN001',
      'insurer': 'Max Bupa',
      'name': 'Health Companion Senior',
      'type': 'Health Insurance',
      'category': 'Senior Citizen',
      'premiumMonthly': 3500,
      'premiumYearly': 40000,
      'coverageAmount': 500000,
      'claimSettlementRatio': 95.2,
      'benefits': ['No Medical Check-up', 'Lifetime Renewal', 'Ayush Treatment'],
      'exclusions': ['Pre-existing diseases (2 year wait)'],
      'riders': ['Personal Accident', 'Hospital Cash'],
      'suitableFor': 'Senior citizens 60+, Retired individuals',
      'notIdealFor': 'Young individuals',
      'readabilityScore': 6,
      'riskScore': 5,
      'iconUrl': '',
    },
    {
      'id': 'SEN002',
      'insurer': 'Star Health',
      'name': 'Star Senior Citizens Red Carpet',
      'type': 'Health Insurance',
      'category': 'Senior Citizen',
      'premiumMonthly': 4000,
      'premiumYearly': 45000,
      'coverageAmount': 750000,
      'claimSettlementRatio': 96.5,
      'benefits': ['Entry up to 75 years', 'Automatic Restoration', 'Outpatient Consult'],
      'exclusions': ['Pre-existing (1 year wait)', 'Cataract (2 year wait)'],
      'riders': ['Hospital Cash', 'Personal Accident'],
      'suitableFor': 'Active seniors, Post-retirement',
      'notIdealFor': 'Below 60 years',
      'readabilityScore': 7,
      'riskScore': 5,
      'iconUrl': '',
    },
    {
      'id': 'SEN003',
      'insurer': 'Care Health',
      'name': 'Care Senior',
      'type': 'Health Insurance',
      'category': 'Senior Citizen',
      'premiumMonthly': 3200,
      'premiumYearly': 36000,
      'coverageAmount': 500000,
      'claimSettlementRatio': 95.5,
      'benefits': ['Affordable Senior Cover', 'AYUSH', 'Pre-hospitalization 60 days'],
      'exclusions': ['Knee replacement (2 years)', 'Hernia (2 years)'],
      'riders': ['Critical Illness', 'Daily Cash'],
      'suitableFor': 'Budget-conscious seniors',
      'notIdealFor': 'Those needing immediate surgeries',
      'readabilityScore': 6,
      'riskScore': 5,
      'iconUrl': '',
    },
    {
      'id': 'SEN004',
      'insurer': 'New India Assurance',
      'name': 'Senior Citizen Mediclaim',
      'type': 'Health Insurance',
      'category': 'Senior Citizen',
      'premiumMonthly': 2800,
      'premiumYearly': 32000,
      'coverageAmount': 300000,
      'claimSettlementRatio': 94.0,
      'benefits': ['Government Backing', 'Wide Network', 'Domiciliary'],
      'exclusions': ['Pre-existing (4 years)', 'Dental'],
      'riders': ['Personal Accident'],
      'suitableFor': 'PSU retirees, Conservative buyers',
      'notIdealFor': 'Premium service seekers',
      'readabilityScore': 5,
      'riskScore': 5,
      'iconUrl': '',
    },
    {
      'id': 'SEN005',
      'insurer': 'HDFC Ergo',
      'name': 'Optima Senior',
      'type': 'Health Insurance',
      'category': 'Senior Citizen',
      'premiumMonthly': 3800,
      'premiumYearly': 43000,
      'coverageAmount': 500000,
      'claimSettlementRatio': 97.0,
      'benefits': ['No Claim Bonus', 'Modern Procedures', 'E-Opinion'],
      'exclusions': ['Joint replacement (1 year)'],
      'riders': ['Care at Home', 'OPD'],
      'suitableFor': 'Tech-savvy seniors, Metro cities',
      'notIdealFor': 'Rural seniors',
      'readabilityScore': 7,
      'riskScore': 4,
      'iconUrl': '',
    },
    
    // ==================== CRITICAL ILLNESS ====================
    {
      'id': 'CRT001',
      'insurer': 'HDFC Life',
      'name': 'Critical Illness Cover',
      'type': 'Critical Illness',
      'category': 'Individual',
      'premiumMonthly': 800,
      'premiumYearly': 9000,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 99.1,
      'benefits': ['Lump Sum Payout', '36 Critical Illnesses', 'Survival Benefit'],
      'exclusions': ['Pre-existing conditions', 'Waiting period ailments'],
      'riders': ['Waiver of Premium'],
      'suitableFor': 'High-stress jobs, Family history of illness',
      'notIdealFor': 'Young healthy individuals',
      'readabilityScore': 8,
      'riskScore': 4,
      'iconUrl': '',
    },
    {
      'id': 'CRT002',
      'insurer': 'ICICI Prudential',
      'name': 'Heart/Cancer Protect',
      'type': 'Critical Illness',
      'category': 'Individual',
      'premiumMonthly': 700,
      'premiumYearly': 8000,
      'coverageAmount': 2500000,
      'claimSettlementRatio': 97.8,
      'benefits': ['Heart & Cancer Focus', 'Income Benefit', 'Premium Return'],
      'exclusions': ['First 90 days', 'Congenital conditions'],
      'riders': ['Additional Cancer Cover'],
      'suitableFor': 'Smokers, Sedentary lifestyle',
      'notIdealFor': 'Comprehensive coverage seekers',
      'readabilityScore': 7,
      'riskScore': 5,
      'iconUrl': '',
    },
    {
      'id': 'CRT003',
      'insurer': 'Bajaj Allianz',
      'name': 'iSecure CI Plan',
      'type': 'Critical Illness',
      'category': 'Individual',
      'premiumMonthly': 650,
      'premiumYearly': 7500,
      'coverageAmount': 500000,
      'claimSettlementRatio': 98.2,
      'benefits': ['50+ Illnesses Covered', 'Early Stage Payout', 'Income Benefit'],
      'exclusions': ['HIV/AIDS', 'Substance abuse'],
      'riders': ['Accidental Death'],
      'suitableFor': 'Budget CI buyers, Supplementary cover',
      'notIdealFor': 'Primary health cover seekers',
      'readabilityScore': 7,
      'riskScore': 4,
      'iconUrl': '',
    },
    
    // ==================== ULIP ====================
    {
      'id': 'ULP001',
      'insurer': 'HDFC Life',
      'name': 'ProGrowth Plus',
      'type': 'ULIP',
      'category': 'Individual',
      'premiumMonthly': 5000,
      'premiumYearly': 55000,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 99.1,
      'benefits': ['Market-linked Returns', 'Tax Benefits', 'Wealth Boosters'],
      'exclusions': ['Market risk applies'],
      'riders': ['Waiver of Premium', 'Accidental Death'],
      'suitableFor': 'Risk-tolerant investors, Long-term wealth',
      'notIdealFor': 'Conservative investors, Short-term',
      'readabilityScore': 6,
      'riskScore': 7,
      'iconUrl': '',
    },
    {
      'id': 'ULP002',
      'insurer': 'ICICI Prudential',
      'name': 'Signature',
      'type': 'ULIP',
      'category': 'Individual',
      'premiumMonthly': 10000,
      'premiumYearly': 115000,
      'coverageAmount': 2500000,
      'claimSettlementRatio': 97.8,
      'benefits': ['Fund Options', 'Loyalty Additions', 'Partial Withdrawal'],
      'exclusions': ['Early surrender charges'],
      'riders': ['Critical Illness', 'Accidental Death'],
      'suitableFor': 'HNIs, Aggressive investors',
      'notIdealFor': 'Risk-averse individuals',
      'readabilityScore': 5,
      'riskScore': 8,
      'iconUrl': '',
    },
    {
      'id': 'ULP003',
      'insurer': 'SBI Life',
      'name': 'Smart Wealth Builder',
      'type': 'ULIP',
      'category': 'Individual',
      'premiumMonthly': 3000,
      'premiumYearly': 34000,
      'coverageAmount': 500000,
      'claimSettlementRatio': 97.2,
      'benefits': ['Multiple Fund Options', 'Auto Rebalancing', 'Online Management'],
      'exclusions': ['Fund management charges'],
      'riders': ['Accidental Death', 'Waiver'],
      'suitableFor': 'First-time ULIP buyers, SBI customers',
      'notIdealFor': 'Those wanting guaranteed returns',
      'readabilityScore': 6,
      'riskScore': 6,
      'iconUrl': '',
    },
    {
      'id': 'ULP004',
      'insurer': 'Bajaj Allianz',
      'name': 'Invest4G',
      'type': 'ULIP',
      'category': 'Individual',
      'premiumMonthly': 4000,
      'premiumYearly': 45000,
      'coverageAmount': 750000,
      'claimSettlementRatio': 98.2,
      'benefits': ['Zero Allocation Charge', 'Unlimited Switches', 'Tax Free Maturity'],
      'exclusions': ['Policy admin charges'],
      'riders': ['Critical Illness'],
      'suitableFor': 'Cost-conscious investors',
      'notIdealFor': 'Traditional plan seekers',
      'readabilityScore': 7,
      'riskScore': 7,
      'iconUrl': '',
    },
    
    // ==================== CHILD PLANS ====================
    {
      'id': 'CHD001',
      'insurer': 'LIC',
      'name': 'Jeevan Tarun',
      'type': 'Child Plan',
      'category': 'Child',
      'premiumMonthly': 3000,
      'premiumYearly': 34000,
      'coverageAmount': 500000,
      'claimSettlementRatio': 98.5,
      'benefits': ['Education Fund', 'Risk Cover', 'Bonus Accumulation'],
      'exclusions': ['Child must be min 90 days old'],
      'riders': ['Waiver of Premium'],
      'suitableFor': 'New parents, Education planning',
      'notIdealFor': 'Short-term goals',
      'readabilityScore': 7,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'CHD002',
      'insurer': 'HDFC Life',
      'name': 'YoungStar Super Premium',
      'type': 'Child Plan',
      'category': 'Child',
      'premiumMonthly': 5000,
      'premiumYearly': 55000,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 99.1,
      'benefits': ['ULIP Returns', 'Education Goal', 'Waiver Benefit'],
      'exclusions': ['Market-linked risk'],
      'riders': ['Waiver of Premium', 'Accidental Death'],
      'suitableFor': 'High-income parents, Long-term planners',
      'notIdealFor': 'Conservative parents',
      'readabilityScore': 6,
      'riskScore': 5,
      'iconUrl': '',
    },
    {
      'id': 'CHD003',
      'insurer': 'ICICI Prudential',
      'name': 'Smart Kid Solution',
      'type': 'Child Plan',
      'category': 'Child',
      'premiumMonthly': 4000,
      'premiumYearly': 45000,
      'coverageAmount': 750000,
      'claimSettlementRatio': 97.8,
      'benefits': ['Flexible Payouts', 'Waiver Benefit', 'Life Cover'],
      'exclusions': ['Early withdrawal penalty'],
      'riders': ['Critical Illness', 'Waiver'],
      'suitableFor': 'Parents of young children',
      'notIdealFor': 'Short-term needs',
      'readabilityScore': 7,
      'riskScore': 4,
      'iconUrl': '',
    },
    {
      'id': 'CHD004',
      'insurer': 'SBI Life',
      'name': 'Smart Scholar',
      'type': 'Child Plan',
      'category': 'Child',
      'premiumMonthly': 2500,
      'premiumYearly': 28000,
      'coverageAmount': 500000,
      'claimSettlementRatio': 97.2,
      'benefits': ['Guaranteed Education Fund', 'Premium Back', 'Life Cover'],
      'exclusions': ['Policy lapses if premiums stopped'],
      'riders': ['Accidental Death of Parent'],
      'suitableFor': 'SBI account holders, Moderate budget',
      'notIdealFor': 'Those wanting aggressive returns',
      'readabilityScore': 8,
      'riskScore': 3,
      'iconUrl': '',
    },
    
    // ==================== SUPER TOP-UP ====================
    {
      'id': 'TOP001',
      'insurer': 'Star Health',
      'name': 'Super Top Up Plan',
      'type': 'Super Top-Up',
      'category': 'Individual',
      'premiumMonthly': 400,
      'premiumYearly': 4500,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 96.5,
      'benefits': ['Low Premium', 'High Cover', 'Works with any Base Plan'],
      'exclusions': ['Deductible applies'],
      'riders': [],
      'suitableFor': 'Those with employer insurance, Base plan holders',
      'notIdealFor': 'First-time health insurance buyers',
      'readabilityScore': 7,
      'riskScore': 2,
      'iconUrl': '',
    },
    {
      'id': 'TOP002',
      'insurer': 'HDFC Ergo',
      'name': 'My Health Suraksha Top Up',
      'type': 'Super Top-Up',
      'category': 'Family',
      'premiumMonthly': 600,
      'premiumYearly': 6800,
      'coverageAmount': 2500000,
      'claimSettlementRatio': 97.0,
      'benefits': ['Family Floater Option', 'No Waiting for Accidents', 'Restore'],
      'exclusions': ['Threshold/deductible', 'Pre-existing'],
      'riders': [],
      'suitableFor': 'Corporate employees, Base plan enhancers',
      'notIdealFor': 'Those without base plan',
      'readabilityScore': 8,
      'riskScore': 2,
      'iconUrl': '',
    },
    {
      'id': 'TOP003',
      'insurer': 'Care Health',
      'name': 'Care Freedom Top Up',
      'type': 'Super Top-Up',
      'category': 'Individual',
      'premiumMonthly': 350,
      'premiumYearly': 4000,
      'coverageAmount': 1500000,
      'claimSettlementRatio': 95.5,
      'benefits': ['Affordable Enhancement', 'Cumulative Bonus', 'Day Care'],
      'exclusions': ['Deductible threshold'],
      'riders': [],
      'suitableFor': 'Budget enhancement, Office insurance toppers',
      'notIdealFor': 'Standalone coverage seekers',
      'readabilityScore': 7,
      'riskScore': 2,
      'iconUrl': '',
    },
    
    // ==================== PERSONAL ACCIDENT ====================
    {
      'id': 'ACC001',
      'insurer': 'ICICI Lombard',
      'name': 'Personal Accident Cover',
      'type': 'Personal Accident',
      'category': 'Individual',
      'premiumMonthly': 200,
      'premiumYearly': 2200,
      'coverageAmount': 2500000,
      'claimSettlementRatio': 96.5,
      'benefits': ['Accidental Death', 'Disability', 'Education Benefit'],
      'exclusions': ['War', 'Nuclear risks', 'Intoxication'],
      'riders': [],
      'suitableFor': 'Frequent travelers, Risky professions',
      'notIdealFor': 'Desk job workers',
      'readabilityScore': 8,
      'riskScore': 2,
      'iconUrl': '',
    },
    {
      'id': 'ACC002',
      'insurer': 'Bajaj Allianz',
      'name': 'Individual Personal Accident',
      'type': 'Personal Accident',
      'category': 'Individual',
      'premiumMonthly': 150,
      'premiumYearly': 1700,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 96.0,
      'benefits': ['Death Benefit', 'Weekly Benefit', 'Medical Expenses'],
      'exclusions': ['Suicide', 'Self-injury'],
      'riders': [],
      'suitableFor': 'Two-wheeler riders, Field workers',
      'notIdealFor': 'Those with comprehensive health',
      'readabilityScore': 9,
      'riskScore': 2,
      'iconUrl': '',
    },
    {
      'id': 'ACC003',
      'insurer': 'Tata AIG',
      'name': 'Accident Guard',
      'type': 'Personal Accident',
      'category': 'Family',
      'premiumMonthly': 400,
      'premiumYearly': 4500,
      'coverageAmount': 5000000,
      'claimSettlementRatio': 96.8,
      'benefits': ['Family Coverage', 'Education Fund', 'Loan EMI Cover'],
      'exclusions': ['Adventure sports (unless declared)'],
      'riders': ['Hospital Cash'],
      'suitableFor': 'Family breadwinners, Loan holders',
      'notIdealFor': 'Retired individuals',
      'readabilityScore': 8,
      'riskScore': 2,
      'iconUrl': '',
    },
    
    // ==================== WOMEN-SPECIFIC ====================
    {
      'id': 'WMN001',
      'insurer': 'HDFC Ergo',
      'name': 'Health Edge Women',
      'type': 'Health Insurance',
      'category': 'Women',
      'premiumMonthly': 1500,
      'premiumYearly': 17000,
      'coverageAmount': 750000,
      'claimSettlementRatio': 97.0,
      'benefits': ['Maternity Cover', 'Breast Cancer', 'Women-specific Illness'],
      'exclusions': ['Infertility', 'Cosmetic'],
      'riders': ['Newborn Cover', 'OPD'],
      'suitableFor': 'Working women, Planning pregnancy',
      'notIdealFor': 'Post-menopausal women',
      'readabilityScore': 8,
      'riskScore': 3,
      'iconUrl': '',
    },
    {
      'id': 'WMN002',
      'insurer': 'Star Health',
      'name': 'Star Women Care',
      'type': 'Health Insurance',
      'category': 'Women',
      'premiumMonthly': 1200,
      'premiumYearly': 13500,
      'coverageAmount': 500000,
      'claimSettlementRatio': 96.5,
      'benefits': ['Women-focused Benefits', 'Maternity', 'Lady Gynaec Network'],
      'exclusions': ['Pre-existing (4 years)'],
      'riders': ['Critical Illness'],
      'suitableFor': 'Young women, Single women',
      'notIdealFor': 'Families needing floater',
      'readabilityScore': 7,
      'riskScore': 3,
      'iconUrl': '',
    },
    
    // ==================== CANCER SPECIFIC ====================
    {
      'id': 'CAN001',
      'insurer': 'Future Generali',
      'name': 'Cancer Protect Plan',
      'type': 'Cancer Insurance',
      'category': 'Individual',
      'premiumMonthly': 300,
      'premiumYearly': 3400,
      'coverageAmount': 1000000,
      'claimSettlementRatio': 95.0,
      'benefits': ['Lump Sum on Diagnosis', 'Income Benefit', 'Premium Waiver'],
      'exclusions': ['Pre-existing cancer', 'First 90 days'],
      'riders': ['Second Opinion'],
      'suitableFor': 'Family history of cancer, Smokers',
      'notIdealFor': 'Those with cancer history',
      'readabilityScore': 8,
      'riskScore': 5,
      'iconUrl': '',
    },
    {
      'id': 'CAN002',
      'insurer': 'HDFC Ergo',
      'name': 'Cancer Mediclaim',
      'type': 'Cancer Insurance',
      'category': 'Individual',
      'premiumMonthly': 500,
      'premiumYearly': 5500,
      'coverageAmount': 1500000,
      'claimSettlementRatio': 97.0,
      'benefits': ['All Stages Covered', 'Treatment Expenses', 'Hospitalization'],
      'exclusions': ['Waiting period cancers'],
      'riders': ['Hospital Cash'],
      'suitableFor': 'High-risk individuals, Preventive coverage',
      'notIdealFor': 'Comprehensive health holders',
      'readabilityScore': 7,
      'riskScore': 4,
      'iconUrl': '',
    },
  ];
}

